name: mind_space
description: MindSpace – Your reflection companion
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 8.1.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.9.1
  flutter_animate: ^4.5.0
  flutter_riverpod: 3.3.1
  go_router: 17.2.3
  flutter_slidable: ^3.1.0
  flutter_test:
    sdk: flutter
  riverpod: 3.2.1
  riverpod_annotation: ^4.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/designs/