// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlq3nGvSl9Jarw806lDImTat7roqtlCg8',
    appId: '1:46130881422:web:17e1d30cb4a6176cb67adf',
    messagingSenderId: '46130881422',
    projectId: 'mindspace-project-9713d',
    authDomain: 'mindspace-project-9713d.firebaseapp.com',
    storageBucket: 'mindspace-project-9713d.firebasestorage.app',
    measurementId: 'G-RVMRVYW2LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzjF0qE_NHTmgBaQKkwBSMOxgoFRQtduw',
    appId: '1:46130881422:android:6f5844c33ddeedd0b67adf',
    messagingSenderId: '46130881422',
    projectId: 'mindspace-project-9713d',
    storageBucket: 'mindspace-project-9713d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrT_-KilYykEqci7Z64kU7SEfDcz_vGtQ',
    appId: '1:46130881422:ios:c1598869f3a1fa56b67adf',
    messagingSenderId: '46130881422',
    projectId: 'mindspace-project-9713d',
    storageBucket: 'mindspace-project-9713d.firebasestorage.app',
    iosClientId: '46130881422-ptuihcq1ka1rhrdiomdbcnv6pdqj9fim.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrT_-KilYykEqci7Z64kU7SEfDcz_vGtQ',
    appId: '1:46130881422:ios:c1598869f3a1fa56b67adf',
    messagingSenderId: '46130881422',
    projectId: 'mindspace-project-9713d',
    storageBucket: 'mindspace-project-9713d.firebasestorage.app',
    iosClientId: '46130881422-ptuihcq1ka1rhrdiomdbcnv6pdqj9fim.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlq3nGvSl9Jarw806lDImTat7roqtlCg8',
    appId: '1:46130881422:web:12c2225fcb3c042fb67adf',
    messagingSenderId: '46130881422',
    projectId: 'mindspace-project-9713d',
    authDomain: 'mindspace-project-9713d.firebaseapp.com',
    storageBucket: 'mindspace-project-9713d.firebasestorage.app',
    measurementId: 'G-Y3Y77GBWMR',
  );
}
